/**
 * AccountDO entity encapsulation table account record.
 * @author LUYL,Generated by the auto build tools .
 * @Time 2020-12-22 14:19:20
 */
package org.web.example.springcloud.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AccountDO {

	// account表主键
	private Long accountId;
	// 账户名称
	private String accountName;
	// 账户号
	private Long accountNo;
	// 逻辑删除标记位
	private String isDelete;

}


